# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - play14-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://play14containerregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_18775a913552446b9def6c0c31ee6671 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_fc9b45e883914765bde29c788b803c47 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: play14containerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_18775a913552446b9def6c0c31ee6671 }}/play14-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'play14-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_71c42592c0fc4a4abcc1ca5995839c87 }}
        images: 'play14containerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_18775a913552446b9def6c0c31ee6671 }}/play14-api:${{ github.sha }}'