# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - play14-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://play14containerregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_49ea280ed2414f93ae5515ab2e6c7b69 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d69aa9f3e7964d5f8cda64198c4abdd7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: play14containerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_49ea280ed2414f93ae5515ab2e6c7b69 }}/play14containerregistry/play14/api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'play14-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ac729c502c2c42b3b618fc7082172fe7 }}
        images: 'play14containerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_49ea280ed2414f93ae5515ab2e6c7b69 }}/play14containerregistry/play14/api:${{ github.sha }}'